### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by danikuci1** [pawelmalak/snippet-box#19]
After pulling latest version from docker hub and running, container reports the following:

```
[2021-10-02 04:10:13.636 UTC+0] [INFO] db: Database connected
[2021-10-02 04:10:13.660 UTC+0] [INFO] db: Found pending migrations. Executing...
[2021-10-02 04:10:13.726 UTC+0] [ERROR] db: Database connection error
```

container never starts and produces no further information. not sure where or what to check

**Comment by pawelmalak** [comment]
Is it a fresh install or are you updating existing container?

**Comment by loqster** [comment]
Same issue here. 

Fresh install on RPi4 with Docker

**Comment by pawelmalak** [comment]
Can you give the whole command that you used to run the container?

**Comment by loqster** [comment]
Not sure as i have used portainer to deploy. Dont know how to check the exact command it would use. 
But it would be something like that.

docker run --name snippet-box --network host -v snippet-box:/app/data pawelmalak/snippet-box:arm

**Comment by pawelmalak** [comment]
Can you add `-e NODE_ENV=development` variable to the container and check the logs again?

**Comment by pawelmalak** [comment]
Can you add `-e NODE_ENV=development` variable to the container and check logs again?

**Comment by loqster** [comment]
The container started but failed with a different error. 

> [2021-10-04 09:13:25.212 UTC+0] [INFO] db: Database connected,
[2021-10-04 09:13:25.280 UTC+0] [INFO] db: Found pending migrations. Executing...,
[2021-10-04 09:13:25.281 UTC+0] [DEV] db: Executing 01_pinned_snippets.js migration,
[2021-10-04 09:13:25.281 UTC+0] [DEV] db: Executing 02_tags.js migration,
[2021-10-04 09:13:25.332 UTC+0] [ERROR] db: Database connection error,
DatabaseError [SequelizeDatabaseError]: SQLITE_ERROR: duplicate column name: isPinned,
    at Query.formatError (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16),
    at Query._handleQueryResponse (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18),
    at afterExecute (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27),
    at Statement.errBack (/app/node_modules/sqlite3/lib/sqlite3.js:14:21),
From previous event:,
    at /app/node_modules/umzug/lib/index.js:116:62,
    at processImmediate (internal/timers.js:464:21),
From previous event:,
    at /app/node_modules/umzug/lib/index.js:112:43,
From previous event:,
    at Umzug.execute (/app/node_modules/umzug/lib/index.js:112:9),
    at Umzug._run (/app/node_modules/umzug/lib/index.js:279:19),
    at Umzug.<anonymous> (/app/node_modules/umzug/lib/index.js:307:21),
From previous event:,
    at Umzug._run (/app/node_modules/umzug/lib/index.js:306:10),
    at Umzug.up (/app/node_modules/umzug/lib/index.js:198:17),
    at /app/build/db/index.js:54:21,
    at Generator.next (<anonymous>),
    at fulfilled (/app/build/db/index.js:5:58) {,
  parent: [Error: SQLITE_ERROR: duplicate column name: isPinned] {,
    errno: 1,,
    code: 'SQLITE_ERROR',,
    sql: 'ALTER TABLE `snippets` ADD `isPinned` INTEGER DEFAULT 0;',
  },,
  original: [Error: SQLITE_ERROR: duplicate column name: isPinned] {,
    errno: 1,,
    code: 'SQLITE_ERROR',,
    sql: 'ALTER TABLE `snippets` ADD `isPinned` INTEGER DEFAULT 0;',
  },,
  sql: 'ALTER TABLE `snippets` ADD `isPinned` INTEGER DEFAULT 0;',,
  parameters: undefined,
}

**Comment by pawelmalak** [comment]
So I was able to reproduce it on both platforms when I messed up volume path in docker run command. If you are on RPi can you try to run container manually and check if it works?

```bash
mkdir /home/pi/tmpdata
docker run -ti -p 5030:5000 -v /home/pi/tmpdata:/app/data -e NODE_ENV=development pawelmalak/snippet-box:arm
```

**Comment by loqster** [comment]
Ran manually as requested and it works. 


> docker` run -ti -p 5030:5000 -v /home/pi/tmpdata:/app/data -e NODE_ENV=development pawelmalak/snippet-box:arm
[2021-10-04 09:27:35.662 UTC+0] [INFO] db: Database connected
[2021-10-04 09:27:35.718 UTC+0] [INFO] db: Found pending migrations. Executing...
[2021-10-04 09:27:35.720 UTC+0] [DEV] db: Executing 00_initial.js migration
[2021-10-04 09:27:35.720 UTC+0] [DEV] db: Executing 01_pinned_snippets.js migration
[2021-10-04 09:27:35.721 UTC+0] [DEV] db: Executing 02_tags.js migration
[2021-10-04 09:27:35.877 UTC+0] [INFO] server: Server is working on port 5000 in development mode

**Comment by loqster** [comment]
Also tried via portainer with a pre created named volume and with the "NODE_ENV=development" env during containers creation and it also started without the previous issues.

**Comment by pawelmalak** [comment]
Glad it worked

@danikuci1 I'm suspecting that your error is also caused by incorrect volume mapping. Please check if both host and container paths are correct.

**Comment by rehatiel** [comment]
If you use a 'bind' instead of a 'volume' with portainer, it seems to work. 
![image](https://user-images.githubusercontent.com/3809992/141214110-5c8d525b-8033-4c18-804f-3686d2cd695b.png)
